[tox]
isolated_build = true
envlist =
	py{310,311,312,313,314}-django{52}
	py{312,313,314}-django{60}

[gh-actions]
python =
	3.10: py310
	3.11: py311
	3.12: py312
	3.13: py313
	3.14: py314

[testenv]
setenv = PYTHONPATH={toxinidir}
deps =
	django52: Django>=5.2,<5.3
	django60: Django>=6.0,<6.1
allowlist_externals =
	poetry
	sh
skip_install = true
commands =
	poetry export --with=dev --without-hashes -o {toxworkdir}/requirements.txt
	sh -c 'grep -v "^[dD]jango==" {toxworkdir}/requirements.txt | poetry run pip install --no-deps -r /dev/stdin'
	pytest --isort --flake8 --black --cov
